#!/bin/bash

function do_setup() {
    git remote add -f saiku https://github.com/standino/saiku.git
    git subtree add --prefix=saiku saiku master --squash
}


function do_build_saiku(){
    cd ../saiku
    mvn clean install -DskipTests=true
    cd -
}

function do_saiku-ui(){
    cd ../saiku/saiku-ui
    npm run start2 &
    grunt &
    cd -
}

function do_dev(){
    do_saiku-ui
    cd web
    mvn clean install
    mvn  jetty:run-exploded
    cd -
}

function do_help() {
    cat <<eom
Usage: ./obobd dev | ui
dev: 启动开发环境
ui：启动nodejs
eom
}

function do_release(){
    cd ../saiku/saiku-ui
    mvn clean install
    cd -
    cp -r ../saiku/saiku-ui web/src/main/webapp
}

for OPT in $@ ; do

    echo "执行： $OPT"

    case $OPT in
        # setup)
        #     shift
        #     do_setup $@
        #     exit 0
        #     ;;
        dev)
            do_dev
            ;;

        ui)
            do_saiku-ui
            ;;
        release)
            do_release
            ;;
        *|help)
            do_help
            ;;
    esac

done
